name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: klok

      - name: Initialize
        working-directory: klok
        run: |
          pip3 install -U west
          west init -l .
          west update
          pip3 install -r ../zephyr/scripts/requirements-base.txt

      - name: Build firmware
        working-directory: klok
        run: |
          west build -b pinetime_devkit0 -s app

      - name: Archive firmware
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: klok/build/zephyr/zephyr.*
